#config for BibleBot

HOST = "irc.twitch.tv" #do not change
PORT = 6667 #do not change
PASS = "oauth:k703sj6262agtny4l8cv7emsysydve" #Bible Bot's twitch password token, do not change
IDENT = "Bible_Bot" #do not change
CHANNEL = "cgoeller" #change for the appropriate twitch channel's chat
VERSION = "NIV" #change for your desired version - see www.biblegateway.com for list of translations
CMDDELAY = 10 #delay in seconds for running commands so that chat doesn't get flooded
HELP = "You can use \"!verse [book] [chapter] [verse number]\" for a specific verse, or \"!votd\" for verse of the day." #text printout for !help commmand, do not change
TSLNS = ['21st Century King James Version (KJ21)',  'American Standard Version (ASV)', 'Amplified Bible (AMP)', 'Amplified Bible, Classic Edition (AMPC)', 'BRG Bible (BRG)','Christian Standard Bible (CSB)', 'Complete Jewish Bible (CJB)', 'Contemporary English Version (CEV)', 'Darby Translation (DARBY)', 'Douay-Rheims 1899 American Edition (DRA)', 'Easy-to-Read Version (ERV)', 'English Standard Version (ESV)', 'English Standard Version Anglicised (ESVUK)', 'Expanded Bible (EXB)', '1599 Geneva Bible (GNV)', 'GOD\'S WORD Translation (GW)', 'Holman Christian Standard Bible (HCSB)', 'International Children\'s Bible (ICB)', 'International Standard Version (ISV)', 'Jubilee Bible 2000 (JUB)', 'King James Version (KJV)', 'Authorized (King James) Version (AKJV)', 'Lexham English Bible (LEB)', 'Living Bible (TLB)', 'The Message (MSG)', 'Modern English Version (MEV)', 'Names of God Bible (NOG)', 'New American Bible (Revised Edition) (NABRE)', 'New American Standard Bible (NASB)', 'New Century Version (NCV)', 'New English Translation (NET Bible)', 'New International Reader\'s Version (NIRV)', 'New International Version (NIV)', 'New International Version - UK (NIVUK)', 'New King James Version (NKJV)', 'New Life Version (NLV)', 'New Living Translation (NLT)', 'New Revised Standard Version, Anglicised Catholic Edition (NRSVACE)', 'New Revised Standard Version Catholic Edition (NRSVCE)', 'Orthodox Jewish Bible (OJB)', 'Revised Standard Version Catholic Edition (RSVCE)', 'Tree of Life Version (TLV)', 'The Voice (VOICE)', 'World English Bible (WEB)', 'Young\'s Literal Translation (YLT)',] #translation list for version dropdown