#config for BibleBot

HOST = "irc.twitch.tv" #do not change
PORT = 6667 #do not change
PASS = "oauth:k703sj6262agtny4l8cv7emsysydve" #Bible Bot's twitch password token, do not change
IDENT = "Bible_Bot" #do not change
CHANNEL = "cgoeller" #change for the appropriate twitch channel's chat
VERSION = "NIV" #change for your desired version - see www.biblegateway.com for list of translations
CMDDELAY = 10 #delay in seconds for running commands so that chat doesn't get flooded
HELP = "Hi, I'm Bible_Bot! You can use \"!verse [book] [chapter] [verse number]\" for a specific verse, or \"!votd\" for verse of the day." #text printout for !help commmand, do not change
TSLNS = {'KJ21': '21st Century King James Version (KJ21)', 'ASV': 'American Standard Version (ASV)', 'AMP': 'Amplified Bible (AMP)', 'AMPC': 'Amplified Bible, Classic Edition (AMPC)', 'BRG': 'BRG Bible (BRG)', 'CSB': 'Christian Standard Bible (CSB)', 'CJB': 'Complete Jewish Bible (CJB)', 'CEV': 'Contemporary English Version (CEV)', 'DARBY': 'Darby Translation (DARBY)', 'DRA': 'Douay-Rheims 1899 American Edition (DRA)', 'ERV' : 'Easy-to-Read Version (ERV)', 'ESV': 'English Standard Version (ESV)', 'ESVUK': 'English Standard Version Anglicised (ESVUK)', 'EXB': 'Expanded Bible (EXB)', 'GNV' : '1599 Geneva Bible (GNV)', 'GW': 'GOD\'S WORD Translation (GW)', 'HCSB': 'Holman Christian Standard Bible (HCSB)', 'ICB': 'International Children\'s Bible (ICB)', 'ISV': 'International Standard Version (ISV)', 'JUB': 'Jubilee Bible 2000 (JUB)', 'KJV': 'King James Version (KJV)', 'AKJV' : 'Authorized (King James) Version (AKJV)', 'LEB': 'Lexham English Bible (LEB)', 'TLB': 'Living Bible (TLB)', 'MSG': 'The Message (MSG)', 'MEV': 'Modern English Version (MEV)', 'NOG': 'Names of God Bible (NOG)', 'NABRE': 'New American Bible (Revised Edition) (NABRE)', 'NASB': 'New American Standard Bible (NASB)', 'NCV': 'New Century Version (NCV)', 'NET': 'New English Translation (NET)', 'NIRV': 'New International Reader\'s Version (NIRV)', 'NIV': 'New International Version (NIV)', 'NIVUK': 'New International Version - UK (NIVUK)', 'NKJV': 'New King James Version (NKJV)', 'NLV':  'New Life Version (NLV)', 'NLT': 'New Living Translation (NLT)', 'NRSVACE': 'New Revised Standard Version, Anglicised Catholic Edition (NRSVACE)', 'NRSVCE': 'New Revised Standard Version Catholic Edition (NRSVCE)', 'OJB': 'Orthodox Jewish Bible (OJB)', 'RSVCE': 'Revised Standard Version Catholic Edition (RSVCE)', 'TLV': 'Tree of Life Version (TLV)', 'VOICE': 'The Voice (VOICE)', 'WEB': 'World English Bible (WEB)', 'YLT': 'Young\'s Literal Translation (YLT)'} #translation list for version dropdown, do not change
UIR = True #ui remember these settings, false by default